# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'expo-toys-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for expo-toys-ios
  pod 'Alamofire', '4.8.2'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0'

  target 'expo-toys-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'expo-toys-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
